### ISSUE TITLE
Catch psycopg2.OperationalError

### ISSUE THREAD

**Issue by Zukunftsmusik** [PieInTheSky-Inc/PSS-Fleet-Helper#42]
```
2022-04-13T12:34:26.808525+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
2022-04-13T12:34:26.808526+00:00 app[worker.1]:     self.dialect.do_execute(
2022-04-13T12:34:26.808547+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
2022-04-13T12:34:26.808547+00:00 app[worker.1]:     cursor.execute(statement, parameters)
2022-04-13T12:34:26.808549+00:00 app[worker.1]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) terminating connection due to administrator command
2022-04-13T12:34:26.808550+00:00 app[worker.1]: SSL connection has been closed unexpectedly
2022-04-13T12:34:26.808550+00:00 app[worker.1]: 
2022-04-13T12:34:26.808551+00:00 app[worker.1]: [SQL: SELECT pss_chat_log.pss_chat_log_id AS pss_chat_log_pss_chat_log_id, pss_chat_log.created_at AS pss_chat_log_created_at, pss_chat_log.modified_at AS pss_chat_log_modified_at, pss_chat_log.guild_id AS pss_chat_log_guild_id, pss_chat_log.channel_id AS pss_chat_log_channel_id, pss_chat_log.pss_channel_key AS pss_chat_log_pss_channel_key, pss_chat_log.last_pss_message_id AS pss_chat_log_last_pss_message_id, pss_chat_log.name AS pss_chat_log_name 
2022-04-13T12:34:26.808552+00:00 app[worker.1]: FROM pss_chat_log]
2022-04-13T12:34:26.808552+00:00 app[worker.1]: (Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by Zukunftsmusik** [comment]
The issue always seems to appear in the on_raw_reaction_add event. Full stack trace of such an exception:
```
2023-01-17T12:49:53.196878069Z Ignoring exception in on_raw_reaction_add
2023-01-17T12:49:53.198032267Z Traceback (most recent call last):
2023-01-17T12:49:53.198051936Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-01-17T12:49:53.198058151Z     self.dialect.do_execute(
2023-01-17T12:49:53.198063477Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-01-17T12:49:53.198068844Z     cursor.execute(statement, parameters)
2023-01-17T12:49:53.198073861Z psycopg2.OperationalError: server closed the connection unexpectedly
2023-01-17T12:49:53.198079001Z 	This probably means the server terminated abnormally
2023-01-17T12:49:53.198110416Z 	before or while processing the request.
2023-01-17T12:49:53.198115474Z 
2023-01-17T12:49:53.198120143Z 
2023-01-17T12:49:53.198124807Z The above exception was the direct cause of the following exception:
2023-01-17T12:49:53.198129977Z 
2023-01-17T12:49:53.198134778Z Traceback (most recent call last):
2023-01-17T12:49:53.198139887Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event
2023-01-17T12:49:53.198145063Z     await coro(*args, **kwargs)
2023-01-17T12:49:53.198150060Z   File "/usr/bot/src/cogs/reactionroles.py", line 48, in on_raw_reaction_add
2023-01-17T12:49:53.198155363Z     reaction_roles: _List[_ReactionRole] = _orm.get_all_filtered_by(
2023-01-17T12:49:53.198160378Z   File "/usr/bot/src/model/orm.py", line 86, in get_all_filtered_by
2023-01-17T12:49:53.198165521Z     return get_query(cls, session).filter_by(**kwargs).all()
2023-01-17T12:49:53.198170684Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2772, in all
2023-01-17T12:49:53.198175896Z     return self._iter().all()
2023-01-17T12:49:53.198180666Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
2023-01-17T12:49:53.198185856Z     result = self.session.execute(
2023-01-17T12:49:53.198190666Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
2023-01-17T12:49:53.198195926Z     result = conn._execute_20(statement, params or {}, execution_options)
2023-01-17T12:49:53.198201068Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
2023-01-17T12:49:53.198206311Z     return meth(self, args_10style, kwargs_10style, execution_options)
2023-01-17T12:49:53.198211415Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
2023-01-17T12:49:53.198230016Z     return connection._execute_clauseelement(
2023-01-17T12:49:53.198234563Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
2023-01-17T12:49:53.198239151Z     ret = self._execute_context(
2023-01-17T12:49:53.198243508Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
2023-01-17T12:49:53.198248153Z     self._handle_dbapi_exception(
2023-01-17T12:49:53.198253218Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
2023-01-17T12:49:53.198257959Z     util.raise_(
2023-01-17T12:49:53.198262267Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2023-01-17T12:49:53.198266808Z     raise exception
2023-01-17T12:49:53.198271421Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-01-17T12:49:53.198276218Z     self.dialect.do_execute(
2023-01-17T12:49:53.198280538Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-01-17T12:49:53.198285164Z     cursor.execute(statement, parameters)
2023-01-17T12:49:53.198289436Z sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
2023-01-17T12:49:53.198294013Z 	This probably means the server terminated abnormally
2023-01-17T12:49:53.198298519Z 	before or while processing the request.
2023-01-17T12:49:53.198302919Z 
2023-01-17T12:49:53.198317089Z [SQL: SELECT reaction_role.reaction_role_id AS reaction_role_reaction_role_id, reaction_role.created_at AS reaction_role_created_at, reaction_role.modified_at AS reaction_role_modified_at, reaction_role.channel_id AS reaction_role_channel_id, reaction_role.guild_id AS reaction_role_guild_id, reaction_role.is_active AS reaction_role_is_active, reaction_role.message_id AS reaction_role_message_id, reaction_role.name AS reaction_role_name, reaction_role.reaction AS reaction_role_reaction, reaction_role_change_1.reaction_role_change_id AS reaction_role_change_1_reaction_role_change_id, reaction_role_change_1.created_at AS reaction_role_change_1_created_at, reaction_role_change_1.modified_at AS reaction_role_change_1_modified_at, reaction_role_change_1.reaction_role_id AS reaction_role_change_1_reaction_role_id, reaction_role_change_1.add AS reaction_role_change_1_add, reaction_role_change_1.allow_toggle AS reaction_role_change_1_allow_toggle, reaction_role_change_1.message_channel_id AS reaction_role_change_1_message_channel_id, reaction_role_change_1.message_content AS reaction_role_change_1_message_content, reaction_role_change_1.message_embed AS reaction_role_change_1_message_embed, reaction_role_change_1.role_id AS reaction_role_change_1_role_id, reaction_role_requirement_1.reaction_role_requirement_id AS reaction_role_requirement_1_reaction_role_requirement_id, reaction_role_requirement_1.created_at AS reaction_role_requirement_1_created_at, reaction_role_requirement_1.modified_at AS reaction_role_requirement_1_modified_at, reaction_role_requirement_1.reaction_role_id AS reaction_role_requirement_1_reaction_role_id, reaction_role_requirement_1.role_id AS reaction_role_requirement_1_role_id 
2023-01-17T12:49:53.198333352Z FROM reaction_role LEFT OUTER JOIN reaction_role_change AS reaction_role_change_1 ON reaction_role.reaction_role_id = reaction_role_change_1.reaction_role_id LEFT OUTER JOIN reaction_role_requirement AS reaction_role_requirement_1 ON reaction_role.reaction_role_id = reaction_role_requirement_1.reaction_role_id 
2023-01-17T12:49:53.198338730Z WHERE reaction_role.guild_id = %(guild_id_1)s AND reaction_role.is_active = true AND reaction_role.message_id = %(message_id_1)s]
2023-01-17T12:49:53.198343445Z [parameters: {'guild_id_1': [...], 'message_id_1': 1064793649503813683}]
2023-01-17T12:49:53.198347971Z (Background on this error at: https://sqlalche.me/e/14/e3q8)
```
